name: latihan_rumahan
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # ðŸŽ¨ UI & Fonts
  google_fonts: ^6.2.1

  # ðŸ–¼ Image caching
  cached_network_image: ^3.4.1

  # ðŸ§  State management
  provider: ^6.1.2

  # ðŸ”Š Text To Speech
  flutter_tts: ^4.0.2

  # ðŸ“Š Grafik
  fl_chart: ^0.68.0

  # ðŸ”¥ Firebase
  firebase_core: ^4.3.0
  firebase_auth: ^6.1.3
  cloud_firestore: ^6.1.1
  firebase_database: ^12.1.1

  # ðŸ”‘ Google Sign-In
  google_sign_in: ^7.2.0

  # ðŸ”— SHARE & OPEN LINK
  share_plus: ^7.2.2
  url_launcher: ^6.2.6

  # â¤ï¸ Health Connect / HealthKit
  health: ^12.1.0

  # ðŸ”” LOCAL NOTIFICATION
  flutter_local_notifications: ^17.2.2

  # âœ… EMAIL VALIDATION (WAJIB BUAT LOGIN EMAIL)
  email_validator: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
